/********************************************************************
* GBRProjectDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GBRProjectDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGBRProjectDict();
extern void G__cpp_setup_inheritanceGBRProjectDict();
extern void G__cpp_setup_typetableGBRProjectDict();
extern void G__cpp_setup_memvarGBRProjectDict();
extern void G__cpp_setup_globalGBRProjectDict();
extern void G__cpp_setup_memfuncGBRProjectDict();
extern void G__cpp_setup_funcGBRProjectDict();
extern void G__set_cpp_environmentGBRProjectDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GBRProjectHeaders.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GBRProjectDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GBRProjectDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GBRProjectDictLN_GBRForest;
extern G__linked_taginfo G__GBRProjectDictLN_GBRTree;
extern G__linked_taginfo G__GBRProjectDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GBRProjectDictLN_vectorlEGBRTreecOallocatorlEGBRTreegRsPgR;
extern G__linked_taginfo G__GBRProjectDictLN_reverse_iteratorlEvectorlEGBRTreecOallocatorlEGBRTreegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
